[package]
name = "provable_evm"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
alexandria_bytes = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

